### ISSUE TITLE
Let's finish the excercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-babelarr#1]
Ahoy @babelarr !!!

Here you have some tips to improve the exercise:

- [x] Avoid adding styles until the js code is solid as a solid rock.
- [x] Define a good structure of folders and files for the project
- [x] Add HTML elements for the game: title, label and input, button, space for feedback (`div`, `p`) and number of trials
- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use placeholder attribute instead of value one to show a field's hint
- [x] Define the logic to generate and save the random number (remember we gave you a sample code)
- [x] Define the logic to make the counter work
- [x] Remember to convert input value string to a number
- [x] Extract the feedback painter to a function
- [x] Fix the if's structure: check for the winner option, then the other and then for the rest is enough with an `else` statement
- [x] Watch out for selector names used in querySelector() methods... they must exist in our HTML code!!
- [x] Watch out for constant names used to save DOM references... Do we want to use the DOM reference or that DOM element content (innerHTMl/value)?
- [x] Move variables declaration to the top of the file
- [x] Use `===` instead of `==` for comparisons
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Remove commented code

Here you have a steps guide to complete it ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by babelarr** [comment]
Hi @oneeyedman !!
Thanks for your feedback and sorry about my exercise... I am very disappointed :( I hope I can do better with your tips. 

Thanks again

**Comment by oneeyedman** [comment]
I'm totally sure you will improve the exercise!

**Comment by babelarr** [comment]
Hi!! @oneeyedman  how are you?

Sorry but I couldn't resolve the exercise until today... I'm happy because I know that I can!!
I need to practice more and be calm.

The solution is on brach "fixingEx". Tell me if you need something.

Thanks again for your tips!! :)

**Comment by oneeyedman** [comment]
Good Job @babelarr!!

Merge your solution to Master when you are ready.

**Comment by babelarr** [comment]
Done! :)
